### ISSUE TITLE
Error: Invalid Credentials during upload

### ISSUE THREAD

**Issue by Divide-By-0** [foolo/dkim-lookup#28]
About an hour or so into upload, even now, I get this error: `upload failed: - Error: Invalid Credentials`

**Comment by foolo** [comment]
@Divide-By-0, after investigation, it seems that we have encountered this bug in next-auth:
https://github.com/nextauthjs/next-auth/discussions/6642

there is a solution described in the thread, but unfortunately not a simple one

i'll look at it again in a while, and also try to think of a workaround

**Comment by foolo** [comment]
@Divide-By-0 I have deployed an update with a workaround.
I have tested it for 90 minutes and the access token is now updated and the process continues.
You can try it you want on https://registry.prove.email/upload as usual. Just sign out and sign in again, and then start an Gmail upload and verify that it runs for more than 60 minutes.

**Comment by foolo** [comment]
No reports of this problem since the workaround, closing
