### ISSUE TITLE
Recurring key fetching and selector guessing

### ISSUE THREAD

**Issue by foolo** [foolo/dkim-lookup#38]
might need to be divided in smaller issues

> 
> Yush G, [2024-02-20 09:52]
> how often is the cron running
> 
> Olof, [2024-02-20 10:01]
> right now it's not running at all :) i have not set it up since we switched to render, but when it's set up it can be any interval, maybe once a day is a good interval
> 
> Yush G, [2024-02-20 10:11]
> Seems fine for now, but I think for the most important domains (venmo, Gmail, Outlook, x, twitter, GitHub, hdfc) it should be once an hour
> 
> Olof, [2024-02-20 10:21]
> sure, maybe we also need to guess selectors (like YYYYMMDD format) or something for those? because i have not seen that they actually change the keys, only the selectors (with a new key for the new selector obviously, but the old selector would still have the same key all the time, at least from what i've seen)
> 
> Yush G, [2024-02-20 10:36]
> Yeah
> 
> Yush G, [2024-02-20 10:37]
> So we check like, if 2022 or 2023 is part of the key, then try a YYYY format, maybe m or d is switched, look at all the selectors with 2022 or 2023 in them, there are some weird ones

**Comment by Divide-By-0** [comment]
Some notable selectors with dates include linkedin.com, maila.linkedin.com, and info.wifionboard.com.

**Comment by foolo** [comment]
solved by 6090c790dfc2590f3483f46fec57e47ed5b9607d
